- .gitignore
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/jsLintPlugin.xml
- .idea/misc.xml
- .idea/prettier.xml
#17 이슈 확인
인텔리제이 편집기 사용자들을 위한 설정을 공유하고자 추가합니다.
> 추가될 파일
```
.idea/codeStyles/
.idea/inspectionProfiles/
.idea/jsLintPlugin.xml
.idea/misc.xml
.idea/prettier.xml
```
> feat: 인텔리제이 설정 추가 (#17)

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/docs_change.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
#5 에대한 이슈템플릿 초안입니다.
해당 이슈브랜치로 변경하시고 아래 링크를 클릭하시면 미리보기 가능합니다 개선이 필요한부분 말씀주시면 변경할께요!
[feature_request](https://github.com/do-pa/itdoc/blob/5-%EC%9D%B4%EC%8A%88-%ED%85%9C%ED%94%8C%EB%A6%BF-%EB%8F%84%EC%9E%85-%EC%A0%9C%EC%95%88/.github/ISSUE_TEMPLATE/feature_request.yml)
[docs_change](https://github.com/do-pa/itdoc/blob/5-%EC%9D%B4%EC%8A%88-%ED%85%9C%ED%94%8C%EB%A6%BF-%EB%8F%84%EC%9E%85-%EC%A0%9C%EC%95%88/.github/ISSUE_TEMPLATE/docs_change.yml)
[bug_report](https://github.com/do-pa/itdoc/blob/5-%EC%9D%B4%EC%8A%88-%ED%85%9C%ED%94%8C%EB%A6%BF-%EB%8F%84%EC%9E%85-%EC%A0%9C%EC%95%88/.github/ISSUE_TEMPLATE/bug_report.yml)
> chore : 이슈 템플릿 추가 초안

- examples/express/__tests__/expressApp.test.js
- examples/express/expressApp.js
아래 이슈를 해결하고자 합니다.
#8 
`examples` 디렉토리 하위에 .header() 을 사용하는 테스트 작성
----
close #8
> test: header 기능 테스트 추가

- examples/testframework-compatibility-test/__tests__/compatibility.test.ts
- examples/testframework-compatibility-test/jest.config.json
- examples/testframework-compatibility-test/package.json
- lib/dsl/adapters/MochaAdapter.ts
- lib/dsl/adapters/TestFramework.ts
- lib/dsl/adapters/index.ts
- package.json
- pnpm-lock.yaml
- tsconfig.test.json
> Gh issue 35

- .gitignore
- examples/express/__tests__/expressApp.test.js
- lib/dsl/interface/describeAPI.ts
사용자가 /signup -> signup 했을 때의 오류가 발생되는게 아닌 url에 /를 추가하는 방식으로 사용자의 실수를 줄여주는 방향으로 UX를 개선했습니다.
relate #11
close #11
> feat: 사용자가 실수로 /를 빼드렸을 때의 대한 UX 개선

- script/llm/index.ts
- script/makedocs/index.ts
> refactor: script내부 console.log를 logger화

- lib/dsl/interface/describeAPI.ts
> fix: 경로 여러번 설정되는 문제 해결

- examples/express/package.json
- examples/testframework-compatibility-test/package.json
- lib/dsl/generator/builders/operation/ResponseBuilder.ts
close https://github.com/do-pa/itdoc/issues/49
> fix: jest stack trace log 버그 수정

- examples/express/__tests__/expressApp.test.js
- examples/express/expressApp.js
- lib/dsl/test-builders/ResponseBuilder.ts
- lib/dsl/test-builders/TestCaseConfig.ts
close #62 
예제에 들어가있는 jwt 토큰은 itdoc을 기반으로 만들어진 토큰입니다.
커스텀 헤더 및 authorization 헤더까지 잘 검사하는 것을 볼 수 있습니다.
> feat: res().header() 구현

- tsup.config.ts
> 번들링 결과물에 필요한 종속성이 포함되도록 변경

- .github/workflows/deploy-docs.yml
- itdoc-doc/README.md
실패 파이프라인 정보 : https://github.com/do-pa/itdoc/actions/runs/14394583790/job/40367882035
- `pnpm` 설치 전에 `Set up Node.js`에서 pnpm을 캐싱하려 발생한 문제로 보임.
- 해당 부분 수정
- 문서 폴더 (`itdoc-doc` 변수화)
> pages 배포되지 않는 오류 해결

- README.md
> 배포준비 1단계 : README 업데이트

- examples/express/expressApp.js
- lib/dsl/generator/TestEventManager.ts
- lib/dsl/generator/index.ts
- lib/dsl/interface/describeAPI.ts
- lib/dsl/interface/itDoc.ts
- package.json
- script/makedocs/index.ts
> feat: makedocs(md, html) 내재화

- CONTRIBUTING.md
> 배포준비 2단계 : 기여 가이드라인 추가

- package.json
빨간색 부분 수정 https://itdoc.kr 로 수정
closed #86
> Update project homepage URL to point to itdoc.kr

- .github/workflows/release-please.yml
메인에 병합되지도 않았는데, 배포 PR이 업로드되는 문제 발생.
이를 해결하고자 합니다.
> Update release-please.yml to check head_branch for main

- examples/express/expressApp.js
- package.json
테스트 정상작동합니다. 
relate https://github.com/do-pa/itdoc/issues/87
> feat: support Node.js >=20

- examples/express/expected/oas.json
- lib/__tests__/unit/dsl/OpenAPIGenerator.test.ts
- lib/dsl/generator/OpenAPIGenerator.ts
- lib/dsl/generator/builders/operation/SecurityBuilder.ts
> fix: oas 204응답 유형 수정

- itdoc-doc/docs/api-reference/interface.mdx
- itdoc-doc/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/interface.mdx
describeAPI에 넘기는 `app`이 어떤식으로 구성되어있는지 드러내도록 변경했씁니다.
> docs: describeAPI에 넘길 app 인스턴스 예시를 상세하게 수정

- itdoc-doc/docs/guides/integration-test-runner.mdx
- itdoc-doc/i18n/ko/docusaurus-plugin-content-docs/current/guides/integration-test-runner.mdx
itdoc 테스트에서 모킹을 사용하는 예시를 추가했습니다.
> docs: Add itdoc with mocking example

- .gitignore
- examples/.gitignore
relate https://github.com/do-pa/itdoc/issues/162
> fix: gitignore에 examples/express-ts/docs/ 추가

- .github/ISSUE_TEMPLATE/feature_request.yml
- examples/express-ts/package.json
> 29 bug 이슈 생성 시 우선순위 라벨이 자동으로 적용되지 않음

- bin/index.ts
- lib/config/getOutputPath.ts
- lib/config/readPackageJson.ts
- package.json
- pnpm-lock.yaml
- script/llm/index.ts
- script/llm/loader/index.ts
- script/llm/parser/index.ts
- script/llm/parser/interface.ts
- script/llm/parser/utils/extractValue.ts
- script/llm/parser/utils/flattenTree.ts
- script/llm/prompt/index.ts
- tsup.config.ts
relate #168
테스트 명령어
```
rm -rf ../itdoc-test11
pnpm run build && pnpm link --global
mkdir ../itdoc-test11 && cd ../itdoc-test11
npm init -y
pnpm link itdoc
pnpm exec itdoc generate -a ../itdoc/examples/express/expressApp.js -e ../.env
```
GPT 기반으로 생성된 output.js 
```js
const app = require
const { describeAPI, itDoc, HttpStatus, field, HttpMethod } = require("itdoc")
const targetApp = app
describeAPI(
HttpMethod.POST,
"/signup",
{
summary: "회원 가입 API",
tag: "Auth",
description: "사용자로부터 아이디와 패스워드를 받아 회원가입을 수행합니다.",
},
targetApp,
(apiDoc) => {
itDoc("회원가입 성공", async () => {
await apiDoc
.test()
.prettyPrint()
.req()
.body({
username: field("사용자 이름", "username"),
password: field("패스워드", "P@ssw0rd123!@#"),
})
.res()
.status(HttpStatus.CREATED)
})
itDoc("아이디를 입력하지 않으면 회원가입 실패한다.", async () => { …
```
> feat: API 테스트 명세서 자동 생성을 위한 Express 앱 분석 기능구현

- README.md
- package.json
> docs: 로고 경로 수정

- README.md
- examples/fastify-js/__test__/app.test.js
- examples/fastify-js/__test__/global-setup.js
- examples/fastify-js/__test__/jest-e2e.json
- examples/fastify-js/package.json
- examples/fastify-js/scripts/check-itdoc-file-generated.js
- examples/fastify-js/src/app.js
- itdoc-doc/docs/guides/framework-guide.mdx
- itdoc-doc/docs/intro.mdx
- itdoc-doc/i18n/ko/docusaurus-plugin-content-docs/current/guides/framework-guide.mdx
- itdoc-doc/i18n/ko/docusaurus-plugin-content-docs/current/intro.mdx
- package.json
- pnpm-lock.yaml
> 아래 커밋단위로 리뷰하심 편하실거예용
----
fastify에서 itdoc 사용방법 문서화 추가.
- `examples/fastify-js` 추가 3aec53eca34266e523d7f3fed898ade922f39977
- 더불어 CI 파이프라인에서 실행 e2e 추가 61c18de231c4d890f6ce477314b68d7bacb704c8
- Fastify 사용자를 위한 itdoc 사용 방법 문서 작성 cb24c85e8c7fd4d0c9722f80ab744f1da56fb15c
-----
closed #185
> docs: write "how to use itdoc documentation" for developers using fastify

- README.md
아래 아티클들에 영감을 얻어 README를 좀 더 매력적으로 개선해 보았습니다.
- https://news.hada.io/topic?id=10941
- https://news.hada.io/topic?id=5379
---
closed #189
> docs: update readme more charming

- script/llm/examples/index.ts
- script/llm/prompt/index.ts
- tsup.config.ts
related #195
빌드 후 examples 가 포함되지 않는것과 기존 llm 스크립트 동작 됨을 테스팅한 모습입니다.
테스팅 명령어는 다음과 같습니다. 
```
pnpm run build && pnpm link --global
mkdir ../itdoc-test5 && cd ../itdoc-test5
pnpm init -y
pnpm link itdoc
pnpm exec itdoc generate -p ../itdoc/md/testspec.md -e ../.env
```
> Chore: Delete the examples path in the deployment dists.

- bin/index.ts
related #177
before
after
test command
```
pnpm build
build/bin/index.js   generate
build/bin/index.js help generate
```
> feat: improve CLI output

- examples/express-ts/jest.config.js
- examples/express-ts/jest.config.ts
- examples/express-ts/package.json
- examples/express-ts/src/__tests__/user.test.ts
- examples/express/package.json
- package.json
- pnpm-lock.yaml
related #199
It was simply a command-related issue. It's not a core issue.
Please check if this problem is also solved at the same time.
https://github.com/do-pa/itdoc/issues/204
> fix: Documentation generation fails when running multiple tests

- examples/express/__tests__/expressApp.test.js
- examples/express/__tests__/expressApp2.test.js
- lib/dsl/generator/commands.ts
refactor(exportOASToJSON): deep‑merge existing OpenAPI spec and unionize path definitions 
related #204
> fix: resolve OAS generation issue with multiple test files in jest

- .github/workflows/ci.yml
- rename CI workflow names to english
> chore: rename CI workflow names to english

- itdoc-doc/docusaurus.config.ts
> deploy docs
